version: '3'
services:
  db:
    container_name: postgres14_openmeteo_db
    hostname: postgres14_db
    build: .
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: open_meteo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p@ssword
